### PR TITLE
Create undria graphic designers

### PR DESCRIPTION
**Pull request by atuhaic**
my name suggestion on the type of project we should use

### CODE REVIEW

**Comment by edmundallan** [comment]
lets think about it and get more ideas

**Comment by edmundallan** [comment]
hello people hope every one is doing well

**Comment by atuhaic** [comment]
Good and you?

**Comment by atuhaic** [comment]
happy new year friends

**Comment by atuhaic** [comment]
hello members, this is our e-commerce group.
[admin category.pdf](https://github.com/edmundallan/e-commerce/files/5925513/admin.category.pdf)
[admin login.pdf](https://github.com/edmundallan/e-commerce/files/5925514/admin.login.pdf)
[insertproduct.pdf](https://github.com/edmundallan/e-commerce/files/5925515/insertproduct.pdf)
[login page.pdf](https://github.com/edmundallan/e-commerce/files/5925517/login.page.pdf)
[manage product.pdf](https://github.com/edmundallan/e-commerce/files/5925519/manage.product.pdf)
[my account page.pdf](https://github.com/edmundallan/e-commerce/files/5925520/my.account.page.pdf)
[my cart page.pdf](https://github.com/edmundallan/e-commerce/files/5925521/my.cart.page.pdf)
[track order page.pdf](https://github.com/edmundallan/e-commerce/files/5925524/track.order.page.pdf)
[wishlist page.pdf](https://github.com/edmundallan/e-commerce/files/5925525/wishlist.page.pdf)

**Pull request merged**
